### ISSUE TITLE
Add support for secondary visualization options

### ISSUE THREAD

**Issue by dogonthehorizon** [Nike-Inc/signal_analog#14]
Charts now support more visualization options that aren't captured by `signal_analog`. We should support `options.secondaryVisualization`  from the Sfx docs here:

https://developers.signalfx.com/reference#create-chart

This should _probably_ be done in similar style to the [PlotType enum](https://github.com/Nike-Inc/signal_analog/blob/1e3714ac8388bd7ec06dd88d66dd81fc3a218620/signal_analog/charts.py#L126-L131).

**Comment by greatestusername** [comment]
Added by ya boy.
https://github.com/Nike-Inc/signal_analog/pull/73
