### ISSUE TITLE
Support legendOptions on List charts

### ISSUE THREAD

**Issue by jrduncans** [Nike-Inc/signal_analog#42]
Add with_legend_options support to ListChart

**Comment by dogonthehorizon** [comment]
Documentation:
https://developers.signalfx.com/reference#create-chart
All keys starting with `options.legendOptions`

This is the current implementation:
https://github.com/Nike-Inc/signal_analog/blob/7bb0f0c6fa8f7bf56c660bbf3a76e7764a97c67e/signal_analog/charts.py#L363-L368

Any PR fixing this ticket should share the implementation between both chart types.

**Comment by vidsPersonalUsername** [comment]
Closed in #61
