### ISSUE TITLE
The top function for a flow is broken

### ISSUE THREAD

**Issue by jrduncans** [Nike-Inc/signal_analog#43]
It takes in a `by` and `over` property, but should take in `count`, `percentage`, and `by`. See https://developers.signalfx.com/reference#top-method

**Comment by agilefall** [comment]
This has been added to the 2.0 branch: https://github.com/Nike-Inc/signal_analog/commit/7be4b30a490bba5f39a741f678ea19dfb26f2cac  

I'm not sure if it should be closed.

**Comment by dogonthehorizon** [comment]
Yar, thanks @agilefall . I'm gonna create a release in GH to track the stuff that we'll be putting in there. Should be available in just a moment!

**Comment by dogonthehorizon** [comment]
This has been released.
