### ISSUE TITLE
Update method signatures

### ISSUE THREAD

**Issue by dogonthehorizon** [Nike-Inc/signal_analog#50]
The following methods should have their signatures updated to match upstream:
- [x] bottom(count=None, percentage=None, by=None)
- [x] Count —> split into count by and count over
- [x] Delta —> no args
- [x] Dimensions not supported
- [x] ewma support over
- [x] double_ewma
- [x] Remove map support
- [x] Max —> split into max by and max over
- [x] Mean —> split into mean by and mean over
- [x] mean_plus_stddev(self, by=None, over=None) ;; by and over separate functions; accept stdev keyword arg
- [x] Median —> split into median by and median over
- [x] Min —> split in two
- [x] Percentile —> split in two and add percentile keyword arg
- [x] Pow —> add zero kwarg variant
- [x] Promote sig needs to change drastically
    - promote(property), promote([property, ...]), promote(by=None), promote(property, ...)
- [x] Random —> add count kwarg
- [x] Size —> split into by and over functions
- [x] Stdev —> split into by and over functions
- [x] Sum —> split into by and over functions
- [x] Timeshift —> remove kwarg
- [x] Top —> count, percentage, by
- [x] Variance —> split into by and over functions

Needs a ticket:
- [x] Fill not supported
- [x] Integrate not supported
- [x] Kpss not supported
- [x] Rateofchange is new

Docs:
https://developers.signalfx.com/reference#signalflow-stream-methods-1

**Comment by agilefall** [comment]
@dogonthehorizon I don't have access to click the checkboxes for "fill"..."rateofchange".  Can you mark them as done?  Thanks

**Comment by dogonthehorizon** [comment]
This has been released.
