### ISSUE TITLE
Heatmaps don't support alternate color palettes or other comparisons

### ISSUE THREAD

**Issue by tlisonbee** [Nike-Inc/signal_analog#88]
Heatmaps support multiple thresholds but don't appear able to support alternate color palettes or other comparisons such as `>=`, `<=`, etc.

See colorScale2 options in API here,
https://developers.signalfx.com/charts_reference.html#operation/Create%20Single%20Chart

**Comment by dogonthehorizon** [comment]
Proposed implementation added in #111

**Comment by dogonthehorizon** [comment]
Completed as part of #111
